BidBot/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('nations/mabiweb/', include('nations_mabiweb_bidbot.urls')),
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('profile')), name='password_change'),
    path('accounts/profile/', views.profile, name='profile'),
    path('admin/', admin.site.urls),
]

nations_mabiweb_bidbot/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'nations_mabiweb_bidbot'
urlpatterns = [
    path('', TemplateView.as_view(template_name='nations_mabiweb_bidbot/home.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='nations_mabiweb_bidbot/about.html'), name='about'),
    path('algorithm/', TemplateView.as_view(template_name='nations_mabiweb_bidbot/algorithm.html'), name='algorithm'),
    path('setup/', TemplateView.as_view(template_name='nations_mabiweb_bidbot/setup.html'), name='setup'),
    path('howto/', TemplateView.as_view(template_name='nations_mabiweb_bidbot/howto.html'), name='howto'),
    path('add-username/', views.add_mabiweb_username, name='add_mabiweb_username'),
    path('verify-username/', views.verify_mabiweb_username, name='verify_mabiweb_username'),
    path('verify-username-failure/', views.verify_mabiweb_username_failure, name='verify_mabiweb_username_failure'),
    path('remove-username/', views.remove_mabiweb_username, name='remove_mabiweb_username'),
    path('initiate/', views.initiate, name='initiate'),
    path('initiate-failure/', views.initiate_failure, name='initiate_failure'),
    path('<int:pk>/bid/', views.bid, name='bid'),
    path('<int:pk>/rank/', views.rank, name='rank'),
    path('<int:pk>/confirm/', views.confirm, name='confirm'),
    path('<int:pk>/', views.results, name='results'),
]

nations_mabiweb_bidbot/models.py
from django.db import models
from django.contrib.auth.models import User

class MaBiWebUsername(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=200)
    def __str__(self):
        return f'{self.username}'

class Match(models.Model):
    match_id = models.IntegerField(default=0, primary_key=True)
    def __str__(self):
        return f'MaBiWeb match {self.match_id}'

class Player(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    def __str__(self):
        return f'{self.name} (in {self.match})'

class Nation(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    def __str__(self):
        return f'{self.name} (in {self.match})'

class Bid(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    nation = models.ForeignKey(Nation, on_delete=models.CASCADE)
    twice_bid_value = models.IntegerField(default=0)
    rank = models.IntegerField(default=0)
    def __str__(self):
        return f'{self.twice_bid_value/2.0:.1f} (for {self.nation.name} by {self.player.name} in {self.match})'

nations_mabiweb_bidbot/forms.py
from django import forms
from django.core import validators

class BidForm(forms.Form):
    def __init__(self, match, possible_usernames, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if len(possible_usernames) > 1:
            self.fields['player'] = forms.ChoiceField(label='Bid as', choices=zip(possible_usernames, possible_usernames))
        for nation in match.nation_set.all():
            self.fields[f'bid_for_{nation.name}'] = forms.CharField(label=nation.name, max_length=5, validators=[validators.RegexValidator(r'^(\d+)((?:\.[05])?)$')])

ordinals = ('zeroth', 'first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth', 'tenth', 'eleventh', 'twelfth')

class RankForm(forms.Form):
    def __init__(self, bids, *args, **kwargs):
        super().__init__(*args, **kwargs)
        player_bid_values = sorted(set(bids.values()), reverse=True)
        self.nation_sets = []
        for bid_value in player_bid_values:
            nations_with_bid_value = [nation for (nation, bid_for_nation) in bids.items() if bid_for_nation == bid_value]
            if len(nations_with_bid_value) == 1:
                continue
            self.nation_sets.append(nations_with_bid_value)
            ranks = ordinals[1:len(nations_with_bid_value)+1]
            choice_list = [('', '')] + [(rank, rank.capitalize()) for rank in ranks]
            for nation in nations_with_bid_value:
                self.fields[nation] = forms.ChoiceField(label=nation, choices=choice_list)

    def clean(self):
        cleaned_data = super().clean()
        for nation_set in self.nation_sets:
            nation_ranks = []
            for nation in nation_set:
                nation_ranks.append(cleaned_data.get(nation))
            if len(nation_ranks) != len(set(nation_ranks)):
                raise forms.ValidationError('Non-unique rankings', code='not_unique')
        return cleaned_data

class MatchForm(forms.Form):
    match_id = forms.CharField(label='MaBiWeb match ID', validators=[validators.RegexValidator(r'^\d+$')])

class MaBiWebUsernameForm(forms.Form):
    help_text = 'Must exactly match your MaBiWeb username. Case sensitive.'
    username = forms.CharField(label='MaBiWeb username', help_text=help_text)
    mabiweb_uid = forms.CharField(label='MaBiWeb user ID', validators=[validators.RegexValidator(r'^\d+$')])

nations_mabiweb_bidbot/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.html import format_html

import re
import secrets
import base64
import urllib.request

from .models import MaBiWebUsername, Match, Player, Nation, Bid
from .forms import BidForm, RankForm, MatchForm, MaBiWebUsernameForm, ordinals

@login_required
def add_mabiweb_username(request):
    if request.method == 'POST':
        form = MaBiWebUsernameForm(request.POST)
        if form.is_valid():
            request.session['username'] = form.cleaned_data.get('username')
            request.session['mabiweb_uid'] = form.cleaned_data.get('mabiweb_uid')
            return redirect('nations_mabiweb_bidbot:verify_mabiweb_username')
    else:
        form = MaBiWebUsernameForm()
    return render(request, 'nations_mabiweb_bidbot/add_mabiweb_username.html', {'form': form})

@login_required
def verify_mabiweb_username(request):
    if request.method == 'POST':
        username = request.session.pop('username', None)
        mabiweb_uid = request.session.pop('mabiweb_uid', None)
        verification_code = request.session.pop('verification_code', None)
        if username is None or mabiweb_uid is None or verification_code is None:
            return redirect('nations_mabiweb_bidbot:home')
        mabiweb_profile_url = f'http://www.mabiweb.com/modules.php?name=Forums&file=profile&mode=viewprofile&u={mabiweb_uid}'
        try:
            mabiweb_profile_page = urllib.request.urlopen(mabiweb_profile_url).read().decode('iso-8859-1')
        except:
            mabiweb_profile_page = ''
        if not (f'>Viewing profile :: {username}</th>' in mabiweb_profile_page and verification_code in mabiweb_profile_page):
            request.session['username'] = username
            request.session['mabiweb_uid'] = mabiweb_uid
            return redirect('nations_mabiweb_bidbot:verify_mabiweb_username_failure')
        (username, new_username) = MaBiWebUsername.objects.get_or_create(user=request.user, username=username)
        if new_username:
            username.save()
        return redirect('profile')
    else:
        username = request.session.pop('username', None)
        mabiweb_uid = request.session.pop('mabiweb_uid', None)
        if username is None or mabiweb_uid is None:
            return redirect('nations_mabiweb_bidbot:home')
        verification_code = secrets.token_hex(8)
        request.session['username'] = username
        request.session['mabiweb_uid'] = mabiweb_uid
        request.session['verification_code'] = verification_code
        return render(request, 'nations_mabiweb_bidbot/verify_mabiweb_username.html', {'username': username, 'verification_code': verification_code})

@login_required
def verify_mabiweb_username_failure(request):
    username = request.session.pop('username', None)
    mabiweb_uid = request.session.pop('mabiweb_uid', None)
    if username is None or mabiweb_uid is None:
        return redirect('nations_mabiweb_bidbot:home')
    return render(request, 'nations_mabiweb_bidbot/verify_mabiweb_username_failure.html', {'username': username, 'mabiweb_uid': mabiweb_uid})

@login_required
def remove_mabiweb_username(request):
    if request.method == 'GET':
        username = request.GET.get('username')
        username = request.user.mabiwebusername_set.get(username=username)
        return render(request, 'nations_mabiweb_bidbot/remove_mabiweb_username.html', {'username': username})
    elif request.method == 'POST':
        username = request.POST.get('username')
        username = request.user.mabiwebusername_set.get(username=username)
        username.delete()
        return redirect('profile')
    return redirect('home')

@login_required
def initiate(request):
    if request.method == 'POST':
        form = MatchForm(request.POST)
        if form.is_valid():
            match_id = form.cleaned_data.get('match_id')
            if not Match.objects.filter(match_id=match_id).exists():
                match_url = f'http://www.mabiweb.com/modules.php?name=GM_Nations&g_id={match_id}&op=view_game_reset'
                try:
                    match_page = urllib.request.urlopen(match_url).read().decode('iso-8859-1')
                    players = re.findall(r'<IMG src=modules/GM_Nations/images/Disc_\S*\.png\s+style=\'[^\']*\'>(?:<B>)?\b([^\s&<]+)\b', match_page)
                    players = sorted(set(players), key=players.index)
                    nations = re.search(r'Player Boards available:\s*([^<]+)', match_page).group(1).split()
                    (match, new_match) = Match.objects.get_or_create(match_id=match_id)
                    if new_match:
                        match.save()
                        for player_name in players:
                            Player(match=match, name=player_name).save()
                        for nation_name in nations:
                            Nation(match=match, name=nation_name).save()
                except:
                    request.session['match_id'] = match_id
                    return redirect('nations_mabiweb_bidbot:initiate_failure')
            return redirect('nations_mabiweb_bidbot:results', pk=match_id)
    else:
        form = MatchForm()
    return render(request, 'nations_mabiweb_bidbot/initiate.html', {'form': form})

@login_required
def initiate_failure(request):
    match_id = request.session.pop('match_id', None)
    if match_id is None:
        return redirect('nations_mabiweb_bidbot:home')
    return render(request, 'nations_mabiweb_bidbot/initiate_failure.html', {'match_id': match_id})

@login_required
def bid(request, pk):
    match = get_object_or_404(Match, match_id=pk)
    player_names = [player.name for player in match.player_set.all()]
    bid_players = {bid.player.name for bid in match.bid_set.all()}
    usernames = {username.username for username in request.user.mabiwebusername_set.all()}
    possible_usernames = (set(player_names) & usernames) - bid_players
    if not possible_usernames:
        return redirect('nations_mabiweb_bidbot:results', pk=pk)
    possible_usernames = sorted(possible_usernames, key=player_names.index)
    if request.method == 'POST':
        form = BidForm(match, possible_usernames, request.POST)
        if form.is_valid():
            if len(possible_usernames) > 1:
                player = form.cleaned_data.get('player')
            else:
                player = possible_usernames[0]
            bid_values = {nation.name: form.cleaned_data.get(f'bid_for_{nation.name}') for nation in match.nation_set.all()}
            twice_bid_values = {}
            for (nation, bid_value) in bid_values.items():
                m = re.match(r'^(\d+)((?:\.[05])?)$', bid_value)
                twice_bid_values[nation] = (int(m.group(1)) * 2) + (1 if m.group(2) == '.5' else 0)
            request.session['match_id'] = match.match_id
            request.session['player'] = player
            request.session['twice_bid_values'] = twice_bid_values
            if len(twice_bid_values) != len(set(twice_bid_values.values())):
                return redirect('nations_mabiweb_bidbot:rank', pk=pk)
            return redirect('nations_mabiweb_bidbot:confirm', pk=pk)
    else:
        form = BidForm(match, possible_usernames)
    if len(possible_usernames) == 1:
        player = possible_usernames[0]
    else:
        player = None
    return render(request, 'nations_mabiweb_bidbot/bid.html', {'match': match, 'player': player, 'form': form})

def twice_bid_value_to_bid_string(twice_bid_value):
    return f'{twice_bid_value//2}' + ('' if twice_bid_value % 2 == 0 else '.5')

@login_required
def rank(request, pk):
    match_id = request.session.get('match_id', None)
    player = request.session.get('player', None)
    twice_bid_values = request.session.get('twice_bid_values', None)
    if match_id is None or player is None or twice_bid_values is None or match_id != pk:
        return redirect('nations_mabiweb_bidbot:bid', pk=pk)
    match = get_object_or_404(Match, match_id=pk)
    descending_bid_values = sorted(set(twice_bid_values.values()), reverse=True)
    if request.method == 'POST':
        form = RankForm(twice_bid_values, request.POST)
        if form.is_valid():
            rankings = {}
            rank = 0
            for bid_value in descending_bid_values:
                nations_with_bid_value = [nation for (nation, bid_for_nation) in twice_bid_values.items() if bid_for_nation == bid_value]
                if len(nations_with_bid_value) == 1:
                    rankings[nations_with_bid_value[0]] = rank
                else:
                    for nation in nations_with_bid_value:
                        rankings[nation] = rank + ordinals.index(form.cleaned_data.get(nation)) - 1
                rank += len(nations_with_bid_value)
            request.session['rankings'] = rankings
            return redirect('nations_mabiweb_bidbot:confirm', pk=pk)
    else:
        form = RankForm(twice_bid_values)
    nation_sets = []
    for bid_value in descending_bid_values:
        nations_with_bid_value = [nation for (nation, bid_for_nation) in twice_bid_values.items() if bid_for_nation == bid_value]
        if len(nations_with_bid_value) != 1:
            nation_sets.append((nations_with_bid_value, twice_bid_value_to_bid_string(bid_value)))
    return render(request, 'nations_mabiweb_bidbot/rank.html', {'match': match, 'player': player, 'nation_sets': nation_sets, 'form': form})

@login_required
def confirm(request, pk):
    if request.method == 'POST':
        match_id = request.session.pop('match_id', None)
        player = request.session.pop('player', None)
        twice_bid_values = request.session.pop('twice_bid_values', None)
    else:
        match_id = request.session.get('match_id', None)
        player = request.session.get('player', None)
        twice_bid_values = request.session.get('twice_bid_values', None)

nations_mabiweb_bidbot/templates/nations_mabiweb_bidbot/add_mabiweb_username.html
{% extends 'nations_mabiweb_bidbot/base.html' %}

{% load widget_tweaks %}

{% block content %}
    <h2>Link your MaBiWeb username to your BidBot account</h2>
    <div class="col-sm-6 px-0">
        <p>
            You can find the complete instructions
            <a href="{% url 'nations_mabiweb_bidbot:setup' %}" target="_blank" rel="noopener noreferrer">here</a>.
        </p>
        <p>
            Find your MaBiWeb user ID by going to the
            <a href="http://www.mabiweb.com/modules.php?name=Forums" target="_blank" rel="noopener noreferrer">MaBiWeb Forum</a>
            page and scrolling to the bottom. You should see your username
            after "Registered Users:". Your username is a link to your forum
            profile page and contains your MaBiWeb user ID at the very end of the
            URL, where it says something like, "u=10222". In that case, you would
            enter "10222" below.
        </p>
    </div>
    <form method="post" action="{% url 'nations_mabiweb_bidbot:add_mabiweb_username' %}">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <div class="col-sm-6 px-0">
                    <label for="id_{{ field.name }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}
                    {% for error_message in field.errors %}
                        <div>
                            <small id="id_{{ field.name }}" class="text-danger">{{ error_message }}</small>
                        </div>
                    {% endfor %}
                    {% if field.help_text %}
                        <div>
                            <small id="id_{{ field.name }}" class="text-mutex">{{ field.help_text }}</small>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Add</button>
    </form>
{% endblock %}

nations_mabiweb_bidbot/templates/nations_mabiweb_bidbot/bid.html
{% extends 'nations_mabiweb_bidbot/base.html' %}

{% load widget_tweaks %}

{% block content %}
    <h2>{{ match }}</h2>
    {% if player %}
        <h3>Bidding as {{ player }}</h3>
    {% endif %}
    <div class="col-sm-6 px-0">
        <p>
            You can find the complete instructions
            <a href="{% url 'nations_mabiweb_bidbot:howto' %}" target="_blank" rel="noopener noreferrer">here</a>.
        </p>
        <p>
            Bids can be in half-point increments.
            Examples of what you can enter
            are, "0", "0.0", "0.5", "1", and so on.
        </p>
    </div>
    <div class="pb-3">
        <form method="post" action="{% url 'nations_mabiweb_bidbot:bid' match.match_id %}">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label" for="id_{{ field.name }}">{{ field.label }}</label>
                    <div class="col-sm-5">
                        {% render_field field class="form-control" %}
                        {% for error_message in field.errors %}
                            <div>
                                <small id="id_{{ field.name }}" class="text-danger">{{ error_message }}</small>
                            </div>
                        {% endfor %}
                        {% if field.help_text %}
                            <div>
                                <small id="id_{{ field.name }}" class="text-mutex">{{ field.help_text }}</small>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">Review Bid</button>
        </form>
    </div>
{% endblock %}

nations_mabiweb_bidbot/templates/nations_mabiweb_bidbot/home.html
{% extends 'nations_mabiweb_bidbot/base.html' %}

{% block content %}
    <h2>BidBot for Nations on MaBiWeb</h2>
    <p>
        <a href="{% url 'nations_mabiweb_bidbot:about' %}">What is this?</a>
    </p>
    <p>
        <a href="{% url 'nations_mabiweb_bidbot:setup' %}">One-time setup</a>
    </p>
    <p>
        <a href="{% url 'nations_mabiweb_bidbot:howto' %}">How to bid</a>
    </p>
    <p>
        <a href="{% url 'nations_mabiweb_bidbot:algorithm' %}">Algorithm</a>
    </p>
    <p>
        <a href="{% url 'nations_mabiweb_bidbot:initiate' %}">Initiate bidding for a match</a>
    </p>
{% endblock %}

nations_mabiweb_bidbot/templates/nations_mabiweb_bidbot/howto.html
{% extends 'nations_mabiweb_bidbot/base.html' %}

{% block content %}
    <h2>How to bid</h2>
    <p>
        First, at least one player has to
        <a href="{% url 'nations_mabiweb_bidbot:initiate' %}">initiate bidding</a>.
        You do this by entering the MaBiWeb match ID. The match ID
        can be found to the left of the match listing on your
        <a href="http://www.mabiweb.com/modules.php?name=Game_Manager" target="_blank" rel="noopener noreferrer">Game Manager</a>
        page. It can also be found near the top of the match page
        where it says, "Nations Game ID=".
    </p>
    <p>
        That will load the match into BidBot and take you to the results
        page for the auction. You should now see a button at the bottom of
        the results page that says, "Bid". If you don't see that button,
        then you probably need to
        <a href="{% url 'nations_mabiweb_bidbot:setup' %}">link your MaBiWeb account</a>
        to your BidBot account.
    </p>
    <p>
        At this point, you can share the link to the results page with the
        other players or they can also initiate, which will just take them
        to the results page. The match will only be loaded once. An example
        results link is
        <a href="{% url 'nations_mabiweb_bidbot:results' 81435 %}">https://bidbot.tabony.net{% url 'nations_mabiweb_bidbot:results' 81435 %}</a>
    </p>
    <p>
        Press the button to bid. You'll see a form where you can enter your
        bid for each of the nations available in the match. You are bidding
        points. Once everyone has bid, each player will be assigned one of
        the nations in the match using the auction
        <a href="{% url 'nations_mabiweb_bidbot:algorithm' %}">algorithm</a>.
        Each player will have to subtract the points they bid for the nation
        they were assigned from their score once the match is complete.
    </p>
    <p>
        Bids can be in half-point increments. Examples of what you can enter
        are, "0", "0.0", "0.5", "1", and so on.
    </p>
    <p>
        You are allowed to bid the same value for more than one nation!
        If you do, then when you press "Review Bid", you will see another
        form where you must rank your preferences for those nations.
        These preferences will be used in the case that you win the bid
        for more than one of these nations.
    </p>
    <p>
        You will have a chance to review your bid before locking it in.
        Once you have confirmed your bid, you will not be able to modify
        it. Choose wisely!
    </p>
    <p>
        After confirming your bid, you will be taken back to the results
        page, where it will say that you have placed a bid.
    </p>
    <p>
        Once all players in the match have placed their bids, the bids
        and the resulting assignment of nations will be revealed!
    </p>
    <p>
        Good luck and have fun!
    </p>
{% endblock %}

nations_mabiweb_bidbot/templates/nations_mabiweb_bidbot/initiate.html
{% extends 'nations_mabiweb_bidbot/base.html' %}

{% load widget_tweaks %}

{% block content %}
    <h2>Initiate bidding</h2>
    <div class="col-sm-6 px-0">
        <p>
            You can find the complete instructions
            <a href="{% url 'nations_mabiweb_bidbot:howto' %}" target="_blank" rel="noopener noreferrer">here</a>.
        </p>
        <p>
            The MaBiWeb match ID can be found to the left of the match listing on your
            <a href="http://www.mabiweb.com/modules.php?name=Game_Manager" target="_blank" rel="noopener noreferrer">Game Manager</a>
            page. It can also be found near the top of the match page
            where it says, "Nations Game ID=".
        </p>
    </div>
    <form method="post" action="{% url 'nations_mabiweb_bidbot:initiate' %}">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <div class="col-sm-6 px-0">
                    <label for="id_{{ field.name }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}
                    {% for error_message in field.errors %}
                        <div>
                            <small id="id_{{ field.name }}" class="text-danger">{{ error_message }}</small>
                        </div>
                    {% endfor %}
                    {% if field.help_text %}
                        <div>
                            <small id="id_{{ field.name }}" class="text-mutex">{{ field.help_text }}</small>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Initiate Bidding</button>
    </form>
{% endblock %}

nations_mabiweb_bidbot/templates/nations_mabiweb_bidbot/initiate_failure.html
{% extends 'nations_mabiweb_bidbot/base.html' %}

{% block content %}
    <h2>Failure to load MaBiWeb Nations match with ID {{ match_id }}!</h2>
{% endblock %}

nations_mabiweb_bidbot/templates/nations_mabiweb_bidbot/rank.html
{% extends 'nations_mabiweb_bidbot/base.html' %}

{% load widget_tweaks nations_mabiweb_bidbot_extras %}

{% block content %}
    <h2>{{ match }}</h2>
    <h3>Bidding as {{ player }}</h3>
    <div class="col-sm-6 px-0">
        <p>
            You can find the complete instructions
            <a href="{% url 'nations_mabiweb_bidbot:howto' %}" target="_blank" rel="noopener noreferrer">here</a>.
        </p>
        <p>
            This step is necessary in case you win the bid
            for multiple nations. BidBot uses your rankings
            to decide which nation you receive. See the
            <a href="{% url 'nations_mabiweb_bidbot:algorithm' %}" target="_blank" rel="noopener noreferrer">algorithm</a>
            page for more details.
        </p>
    </div>
    <form method="post" action="{% url 'nations_mabiweb_bidbot:rank' match.match_id %}">
        {% csrf_token %}
        {% for nation_set, bid_value in nation_sets %}
            <div class='pb-3'>
                <p>Rank your preference for the following nations, for which you bid <strong>{{ bid_value }}</strong>:</p>
                {% for nation in nation_set %}
                    {% with form|get:nation as field %}
                        <div class="form-group row">
                            <label class="col-sm-1 col-form-label" for="id_{{ field.name }}">{{ field.label }}</label>
                            <div class="col-sm-2">
                                {% render_field field class="form-control" %}
                                {% for error_message in field.errors %}
                                    <div>
                                        <small id="id_{{ field.name }}" class="text-danger">{{ error_message }}</small>
                                    </div>
                                {% endfor %}
                                {% if field.help_text %}
                                    <div>
                                        <small id="id_{{ field.name }}" class="text-mutex">{{ field.help_text }}</small>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    {% endwith %}
                {% endfor %}
            </div>
        {% endfor %}
        {% for error_message in form.non_field_errors %}
            <div class="pb-3">
                <span class="text-danger">{{ error_message }}</span>
            </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Review Bid</button>
    </form>
{% endblock %}

nations_mabiweb_bidbot/templates/nations_mabiweb_bidbot/remove_mabiweb_username.html
{% extends 'nations_mabiweb_bidbot/base.html' %}

{% block content %}
    <h2>MaBiWeb username: {{ username.username }}</h2>
    <form method="post" action="{% url 'nations_mabiweb_bidbot:remove_mabiweb_username' %}">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">Remove</button>
        <input type="hidden" name="username" value="{{ username.username }}">
    </form>
{% endblock %}

nations_mabiweb_bidbot/templates/nations_mabiweb_bidbot/verify_mabiweb_username.html
{% extends 'nations_mabiweb_bidbot/base.html' %}

{% block content %}
    <h2>Verify MaBiWeb username: {{ username }}</h2>
    <h2>Code: {{ verification_code }}</h2>
    <div class="col-sm-6 px-0">
        <p>
            You can find the complete instructions
            <a href="{% url 'nations_mabiweb_bidbot:setup' %}" target="_blank" rel="noopener noreferrer">here</a>.
        </p>
        <p>
            You need to display this code on your MaBiWeb forum profile
            to link your accounts. Go to the
            <a href="http://www.mabiweb.com/modules.php?name=Your_Account&op=edituser" target="_blank" rel="noopener noreferrer">Your Info</a>
            MaBiWeb page. (This link should open a new tab.)
            You need to put the verification code into a field
            that will show up on your MaBiWeb forum profile page. The three
            fields that work are, "Your Location", "Your Occupation", and "Your
            Interests", which are in the middle of the page.
            Put this code in any of those three fields and click the
            "Save Changes" button at the bottom of the page. Then come back here
            and press "Verify".
        </p>
    </div>
    <form method="post" action="{% url 'nations_mabiweb_bidbot:verify_mabiweb_username' %}">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">Verify</button>
        <input type="hidden" name="username" value="{{ username }}">
    </form>
{% endblock %}

nations_mabiweb_bidbot/templates/nations_mabiweb_bidbot/verify_mabiweb_username_failure.html
{% extends 'nations_mabiweb_bidbot/base.html' %}

{% block content %}
    <h2>Failure to verify MaBiWeb username {{ username }} with user ID {{ mabiweb_uid }}!</h2>
{% endblock %}