BidBot/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib import admin
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('nations/mabiweb/', include('nations_mabiweb_bidbot.urls')),
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('profile')), name='password_change'),
    path('accounts/profile/', views.profile, name='profile'),
    path('admin/', admin.site.urls),
]

nations_mabiweb_bidbot/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'nations_mabiweb_bidbot'
urlpatterns = [
    path('', TemplateView.as_view(template_name='nations_mabiweb_bidbot/home.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='nations_mabiweb_bidbot/about.html'), name='about'),
    path('algorithm/', TemplateView.as_view(template_name='nations_mabiweb_bidbot/algorithm.html'), name='algorithm'),
    path('setup/', TemplateView.as_view(template_name='nations_mabiweb_bidbot/setup.html'), name='setup'),
    path('howto/', TemplateView.as_view(template_name='nations_mabiweb_bidbot/howto.html'), name='howto'),
    path('add-username/', views.add_mabiweb_username, name='add_mabiweb_username'),
    path('verify-username/', views.verify_mabiweb_username, name='verify_mabiweb_username'),
    path('verify-username-failure/', views.verify_mabiweb_username_failure, name='verify_mabiweb_username_failure'),
    path('remove-username/', views.remove_mabiweb_username, name='remove_mabiweb_username'),
    path('initiate/', views.initiate, name='initiate'),
    path('initiate-failure/', views.initiate_failure, name='initiate_failure'),
    path('<int:pk>/bid/', views.bid, name='bid'),
    path('<int:pk>/rank/', views.rank, name='rank'),
    path('<int:pk>/confirm/', views.confirm, name='confirm'),
    path('<int:pk>/', views.results, name='results'),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
        .navbar-brand
        {
            font-size: 2rem !important;
        }
    </style>
    <title>BidBot</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <a class="navbar-brand mr-auto" href="{% url 'nations_mabiweb_bidbot:home' %}">BidBot</a>
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <span class="navbar-text py-0 mr-3">Welcome, {{ user.username }}!</span>
                <a class="nav-link py-0" href="{% url 'profile' %}">Profile</a>
                <a class="nav-link py-0" href="{% url 'logout' %}">Log Out</a>
            {% else %}
                <a class="nav-link py-0" href="{% url 'login' %}">Log In</a>
                <a class="nav-link py-0" href="{% url 'signup' %}">Sign Up</a>
            {% endif %}
        </div>
    </nav>
    <div class="container py-4">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h2>BidBot</h2>
    <p><a href="{% url 'nations_mabiweb_bidbot:home' %}">BidBot for Nations on MaBiWeb</a></p>
{% endblock %}